#- hosts: router
#  become: true
#  roles:
#    - role: router

- hosts: all
  become: true
  roles:
    - role: commons

- hosts: router
  become: true
  roles:
    - role: router

- hosts: cliente
  become: true
  roles:
    - role: cliente

- hosts: cliente1
  become: true
  roles:
    - role: web
